############################
## HUGO MODULES
############################

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

# Install Hugo Blox blocks
mounts:

  - source: hugo-blox/blox/community
    target: layouts/partials/blox/community/
    includeFiles: '**.html'

  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    includeFiles: '**.css'

  - source: layouts
    target: layouts

  - source: assets
    target: assets
